config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :conversations,:only => [:show, :create]
resources :projects do
  resources :conversations
  resources :chat_messages
  resources :chat_users, :only => :index
    
  match 'chat_settings/:action' => 'chat_settings', :via => [:get, :post]
end

get 'projects/conversations/:id', :to => 'conversations#show'
get 'projects/:id/issues/conversations/:id', :to => 'conversations#show'
get 'projects/:id/settings/conversations/:id', :to => 'conversations#show'

resources :conversations do
  resources :chat_messages
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :project
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :chat_messages, dependent: :destroy



  def name
    if self.project_id
      self.project.name
    else
      self.sender.name.split(" ").first + " AND " + self.recipient.name.split(" ").first
    end
  end
  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  layout false
  before_action :find_project_by_project_id, :only => [:create], :if => :group_message?

  def create
    if group_message?
      (render_403; return false) unless @project.module_enabled?(:redmine_chat) && User.current.allowed_to?(:launch_chat, @project)
      if Conversation.where(:project_id => @project.id).present?
        @conversation = Conversation.where(:project_id => @project.id).first
      else
        @conversation = Conversation.create!(conversation_params)
        @conversation.project_id = @project.id
      end
    else
      @sender = User.find(params[:sender_id])
      @recipient = User.find(params[:recipient_id])

      if Conversation.where("recipient_id = #{@recipient.id} AND sender_id = #{@sender.id}").present?
        @conversation = Conversation.where("recipient_id = #{@recipient.id} AND sender_id = #{@sender.id}").first
      elsif Conversation.where("recipient_id = #{@sender.id} AND sender_id = #{@recipient.id}").present?
        @conversation = Conversation.where("recipient_id = #{@sender.id} AND sender_id = #{@recipient.id}").first
      else
        @conversation = Conversation.create!(conversation_params)
        @conversation.sender_id = @sender.id
        @conversation.recipient_id = @recipient.id
      end
    end
    manual_flag = params[:manual]
    if manual_flag == "1"
      render json: { conversation_id: @conversation.id, manual: manual_flag }
    else 
      render json: { conversation_id: @conversation.id }
    end
  end

  def show
    @conversation = Conversation.find(params[:id])
    if group_message?
 #     @project = @conversation.project
  #    (render_403; return false) unless @project && @project.module_enabled?(:redmine_chat) && User.current.allowed_to?(:launch_chat, @project)
    end
    if (params[:manual] == "1")
      @manual_flag = true
    else
      @manual_flag = false
    end
    # get the setting's max number
    @limit = 5
   # if !ChatSetting[:max_number_in_chat, @project.id].blank?
    #  @limit = ChatSetting[:max_number_in_chat, @project].to_i
   # end
    @messages = ChatMessage.where(conversation: @conversation).limit(@limit).reorder("#{ChatMessage.table_name}.created_at DESC").to_a
    @messages.reverse!
    @message = ChatMessage.new
  end

  private
    def conversation_params
      params.permit(:sender_id, :recipient_id, :project_id)
    end
  
    def interlocutor(conversation)
      User.current == conversation.recipient ? conversation.sender : conversation.recipient
    end

    def group_message?
      return true if params[:project_id]
    end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/show.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>
    <h1><%= @conversation.name %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='fa  fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='fa  fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
</div>
<% if @manual_flag %>
	<div class="chatboxcontent">
<% else %>
	<div class="chatboxcontent" style="display: none;">
<% end %>
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<% if @manual_flag %>
	<div class="chatboxinput">
<% else %>
	<div class="chatboxinput" style="display: none;">
<% end %>
  <%= form_for([@conversation, @message], :remote => true, :html => { id: "conversation_form_#{@conversation.id}"}) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
  <% end %>
</div>
<audio id="chatAudio"><source src="/plugin_assets/redmine_chat/sounds/notification.mp3" type="audio/mpeg"></audio>
<%= subscribe_to conversation_path(@conversation), User.current, @project %>