config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :conversations,:only => [:show, :create]
resources :projects do
  resources :conversations
  resources :chat_messages
  resources :chat_users, :only => :index
    
  match 'chat_settings/:action' => 'chat_settings', :via => [:get, :post]
end

get 'projects/conversations/:id', :to => 'conversations#show'
get 'projects/:id/issues/conversations/:id', :to => 'conversations#show'
get 'projects/:id/settings/conversations/:id', :to => 'conversations#show'

resources :conversations do
  resources :chat_messages
end

app/models/chat_user.rb
class ChatUser < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :conversation
end

app/controllers/chat_users_controller.rb
class ChatUsersController < ApplicationController
  unloadable

  before_action :find_optional_project, :only => :index
  before_action :clear_old_records, :only => :index

  def index
    @users = @project.users
    
    @conversation = @project.conversation
    @chat_messages = ChatMessage.where(conversation: @conversation).limit(5).reorder("#{ChatMessage.table_name}.created_at DESC").to_a
  end
  
  private
    def clear_old_records
      yesterday = Date.yesterday      
      old_chat_users = ChatUser.where("created_at <= ?", yesterday)
      old_chat_users.destroy_all 
    end

end

app/helpers/chat_users_helper.rb
module ChatUsersHelper
  def conversation_interlocutor(conversation)
    conversation.recipient == User.current ? conversation.sender : conversation.recipient
  end
end

app/views/chat_users/index.html.erb
<div class="contextual">
  <% if User.current.allowed_to?(:launch_chat, @project) %>
    <%= link_to l(:label_launch_chat), "#", "data-sid" => User.current.id, "data-pid" => @project.id, :class => 'icon icon-add activate-conversation' %>
  <% end %>
</div>

<h2><%=l(:label_chat)%></h2>
<div class="splitcontentleft">
    <h3><%= l(:label_chat_users) %></h3>
    <div class="chat_user">
      <!-- Table -->
      <table class="table">
        <thead>
        <tr>
          <th>#</th>
          <th><%= l(:field_name) %></th>
          <th><%= l(:label_online_status) %></th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= "#{avatar(user, :size => '14')}#{user ? link_to_user(user) : "-"}".html_safe %></td>
              <td>
              	<% if user == User.current || ChatUser.find_by(:project_id => @project.id, :user_id => user.id) %>
                  <%= image_tag('online.png', :plugin => "redmine_chat") %>
                <% else%>
                  <%= image_tag('offline.png', :plugin => "redmine_chat") %>
                <% end %>
               </td>
               <td>
                  <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
                    "data-sid" => User.current.id, "data-rip" => user.id %>
               </td>
             </tr>
        <% end %>
      </tbody>
      </table>
    </div>
    <hr>
    <h3><%= l(:label_latest_conversations) %></h3>
    <div class="user_chat">
      <% if @chat_messages.any? %>
        <% if User.current.allowed_to?(:show_all_chat_messages, @project) %>
           <p><%= link_to l(:label_chat_messages_view_all), project_chat_messages_path(@project) %></p>
        <% end %>
        <% @chat_messages.each do |chat_message| %>
          <h6><%= avatar(chat_message.user, :size => "24") %><%= authoring chat_message.created_at, chat_message.user %></h6>
          <%= textilizable(chat_message.body) %>
        <% end %>
        <% if User.current.allowed_to?(:show_all_chat_messages, @project) %>
           <p><%= link_to l(:label_chat_messages_view_all), project_chat_messages_path(@project) %></p>
        <% end %>
      <% else %>
           <p><%=l(:tip_no_conversations)%></p>
      <% end %>
    </div>
</div>