config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :conversations,:only => [:show, :create]
resources :projects do
  resources :conversations
  resources :chat_messages
  resources :chat_users, :only => :index
    
  match 'chat_settings/:action' => 'chat_settings', :via => [:get, :post]
end

get 'projects/conversations/:id', :to => 'conversations#show'
get 'projects/:id/issues/conversations/:id', :to => 'conversations#show'
get 'projects/:id/settings/conversations/:id', :to => 'conversations#show'

resources :conversations do
  resources :chat_messages
end

app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id
  
  validates_length_of :body, maximum: 1024
end

app/controllers/chat_messages_controller.rb
class ChatMessagesController < ApplicationController
  before_action :set_chat_message, only: [:destroy]
  
  def create
    @conversation = Conversation.find(params[:conversation_id])
    if @conversation.project
      @project = @conversation.project  
      (render_403; return false) unless @project && @project.module_enabled?(:redmine_chat) && User.current.allowed_to?(:launch_chat, @project)
    end
    @message = @conversation.chat_messages.build(message_params)
    @message.user_id = User.current.id
    @message.save!

    if @conversation.project
      PrivatePub.publish_to "/chatroom", :conversation_id => @conversation.id, :project_id => @project.id
    else
      PrivatePub.publish_to "/chatroom", :conversation_id => @conversation.id
    end
    @path = conversation_path(@conversation)
  end
  
  def index
    @project = Project.find(params[:project_id])
    (render_403; return false) unless @project && @project.module_enabled?(:redmine_chat)
    @limit =  10
    @conversation = @project.conversation
    @chat_messages = ChatMessage.where(conversation: @conversation)
    @chat_messages_count = @chat_messages.count
    @chat_messages_pages = Paginator.new @chat_messages_count, @limit, params['page']
    @offset ||= @chat_messages_pages.offset
    @chat_messages = @chat_messages.order("#{ChatMessage.table_name}.created_at DESC").
                      limit(@limit).
                      offset(@offset).
                      to_a
    respond_to do |format|
      format.html {
        @chat_message = ChatMessage.new # for adding chat_message inline
        render :layout => false if request.xhr?
      }
      format.api
      format.atom { render_feed(@chat_messages, :title => (@project ? @project.name : Setting.app_title) + ": #{l(:label_chat_messages)}") }
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    if User.current.allowed_to?(:delete_chat_messages, @project) || (@chat_message.user == User.current && User.current.allowed_to?(:delete_own_chat_messages, @project))
      if @chat_message.destroy
        flash[:notice] = l(:notice_successful_delete)
      else
        flash[:error] = l(:notice_unsuccessful_save)
      end
      
      respond_to do |format|
        format.html { redirect_to :action => "index", :project_id => @chat_message.conversation.project }
        format.api  { head :ok }
      end
    else
      (render_403; return false)
    end
  end
  
  private
    def message_params
      params.require(:chat_message).permit(:body)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_chat_message
      @chat_message = ChatMessage.find(params[:id])
    end


end

app/helpers/chat_messages_helper.rb
module ChatMessagesHelper
  def self_or_other(message)
    message.user == User.current ? "self" : "other"
  end

  def message_interlocutor(message)
    message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipient
  end
end

app/views/chat_messages/_chat_message.html.erb
<li class="<%= chat_message.user == User.current ? "self" : "other" %>">
  <div class="avatar">
  	<% if avatar(chat_message.user, :size => "32").blank? %>
    	<%= link_to_user(chat_message.user, :format => :username) %>
    <% else %>
    	<%= link_to(avatar(chat_message.user, :size => "32"), user_path(chat_message.user)) %>
    <% end %>
  </div>
  <div class="chatboxmessagecontent">
    <p><%= textilizable(chat_message.body) %></p>
    <time datetime="<%= format_time(chat_message.created_at) %>" title="<%= format_time(chat_message.created_at) %>">
      <%= chat_message.user.name %> • <%= format_time(chat_message.created_at, false) %>
    </time>
  </div>
</li>

app/views/chat_messages/create.js.erb
<% publish_to @path do %>
    var id = "<%= @conversation.id %>";
    var chatbox = $("#chatbox_" + id + " .chatboxcontent");
    var sender_id = "<%= @message.user.id %>";
    var reciever_id = $('meta[name=user-id]').attr("content");

    chatbox.append("<%= j render( partial: @message ) %>");
    chatbox.scrollTop(chatbox[0].scrollHeight);


    if (sender_id != reciever_id) {
        chatBox.chatWith(id);
        chatbox.children().last().removeClass("self").addClass("other");
        chatbox.scrollTop(chatbox[0].scrollHeight);
        chatBox.notify(id);
    }
<% end %>

app/views/chat_messages/index.html.erb
<div class="contextual">
</div>

<h2><%=l(:label_chat_messages)%></h2>

<% if @chat_messages.empty? %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  <% @chat_messages.each do |chat_message| %>
    <h6><%= avatar(chat_message.user, :size => "24") %><%= authoring chat_message.created_at, chat_message.user %></h6>
    <%= textilizable(chat_message.body) %>
    <% if User.current.allowed_to?(:delete_chat_messages, @project) || (chat_message.user == User.current && User.current.allowed_to?(:delete_own_chat_messages, @project)) %>
    <p class="buttons">
      <%= link_to image_tag('delete.png'), project_chat_message_path(chat_message.conversation.project, chat_message),
                                                                      :data => {:confirm => l(:text_are_you_sure)},
                                                                      :method => :delete,
                                                                      :title => l(:button_delete) %>
    </p>
    <% end %>
  <% end %>
<% end %>
<span class="pagination"><%= pagination_links_full @chat_messages_pages %></span>